server:
  port: 8182
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  use-forward-headers: true
  servlet:
    context-path: /uaa
spring:
  cloud:
    nacos:
      discovery:
        server-addr: mshcc:8848
#        server-addr: 192.168.52.131:8848
        cluster-name: MyCluster
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://116.63.144.75 :3306/mshcc_cloud?useUnicode=true&useSSL=false
  application:
    name: mshcc-cloud-back
  http:
    encoding:
      force: true