server:
  port: 8188
spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        #        server-addr: 116.63.144.75:8848
        server-addr: 192.168.52.131:8848
        cluster-name: MyCluster
    gateway:
      routes:
        - id: uaa
          uri: lb://mshcc-cloud-jwt-uaa
          predicates:
            - Path=/uaa/**
        #          filters:
        #            - RewritePath=/(?<segment>.*),/$\{segment}
        - id: order
          uri: lb://security-order
          predicates:
            - Path=/order/**
#          filters:
#            - RewritePath=/(?<segment>.*),/$\{segment}
